server:
  port: 8082
spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #视图 这是默认的配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    #检查模板是否存在，然后再呈现
    check-template-location: true
mybatis:
  type-aliases-package: com.gtk.spring.security.oauth2.server.domain
  mapper-locations: classpath:mapper/*.xml