spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 10102

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    basePackages: com.gtk.dubbo.provider.service
  protocol:
    name: dubbo
    port: -1
    # 高速序列化
    serialization: kryo
  provider:
    # 负载均衡配置的值分别是：random(默认随机)，roundrobin(轮循)，leastactive(最少活跃调用数)，consistenthash(一致性 Hash)
    loadbalance: roundrobin
management:
  endpoints:
    web:
      exposure:
        include: "*"