server:
  port: 8000
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bsp?characterEncoding=utf8&useSSL=false
  redis:
    host: localhost
    password: 123456
    port: 6379
    timeout: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gtk.bsp.entity